### ISSUE TITLE
add sed to count the occurrences of each symbol in a fasta file

### ISSUE THREAD

**Issue by felipelouza** [stephenturner/oneliners#19]
Hi,
maybe it would be interesting to add how to count the occurrences of each symbol in a fasta file: 

`sed '/^>/d;s/\(.\)/\1\n/g' file.fa | sort | uniq -ic`

Best!

**Comment by stephenturner** [comment]
hm, any idea how this scales?

**Comment by felipelouza** [comment]
actually, a little bad.
about 10 minutes for a 200MB file in a personal computer.

**Comment by stephenturner** [comment]
yeah, there are probably better tools to look at nucleotide distribution. may work for small files.
